更新相册地址
youngytj/Qzone_Photo pull request #5
Opened 2017-03-19 10:01 UTC by JJaicmkmy

2017-03-19 11:54 UTC, youngytj commented on qphoto/__init__.py
> +    albumbase1 = "http://photo.qq.com/fcgi-bin/fcg_list_album?uin=" # 如果没有设置密保的相册是通过这个地址访问的
这个URL是怎么得出来的？

2017-03-19 11:56 UTC, JJaicmkmy commented
你原来的地址已经失效了。这个地址是在
https://github.com/yejinmo/QzoneAlbumDownloader/blob/master/README.md 这里找到的。

tianjyan <notifications@github.com>于2017年3月19日 周日下午7:54写道：

> *@youngytj* commented on this pull request.
> ------------------------------
>
> In qphoto/__init__.py
> <https://github.com/youngytj/Qzone_Photo/pull/5#discussion_r106804627>:
>
> > @@ -21,7 +21,7 @@ class QzonePhoto(object):
>      """
>      查询QQ空间相册并下载的类。
>      """
> -    albumbase1 = "http://alist.photo.qq.com/fcgi-bin/fcg_list_album?uin=" # 如果没有设置密保的相册是通过这个地址访问的
> +    albumbase1 = "http://photo.qq.com/fcgi-bin/fcg_list_album?uin=" # 如果没有设置密保的相册是通过这个地址访问的
>
> 这个URL是怎么得出来的？
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/youngytj/Qzone_Photo/pull/5#pullrequestreview-27746033>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOPGieSKBu8eZBKx7rbCyMqP410ri979ks5rnRdfgaJpZM4Mhr6E>
> .
>

2017-03-19 11:57 UTC, tianjyan requested changes

2017-03-19 11:57 UTC, youngytj commented on qphoto/__init__.py
> +    albumbase1 = "http://photo.qq.com/fcgi-bin/fcg_list_album?uin=" # 如果没有设置密保的相册是通过这个地址访问的
试了下，新的URL可以的。但最好能把`photobase1`也改一下。

2017-03-19 11:58 UTC, JJaicmkmy commented
只有 albumbase1 失效了，其它地址都没有问题。

2017-03-19 12:02 UTC, youngytj commented
最好把photobase1的URL也改一下，因为如果`albumbase1`的URL变了的话，`photobase1`的URL可能也会不久就失效。

2017-03-19 12:04 UTC, JJaicmkmy commented
好的，我回去抓包看看。

2017-03-21 11:47 UTC, tianjyan approved these changes

2017-03-21 11:48 UTC, merged